# Generated by Django 3.2.8 on 2021-10-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='workouts_rsvped_for',
            field=models.ManyToManyField(to='workouts.Workout'),
        ),
    ]
