# Generated by Django 3.2.8 on 2021-10-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_athlete_workouts_rsvped_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='email',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_name',
        ),
    ]
