# Generated by Django 3.2.8 on 2021-10-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('workouts', '0002_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
