# Generated by Django 3.2.8 on 2021-10-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20211029_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
