# Generated by Django 3.2.8 on 2021-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20211124_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excuserequest',
            name='explanation',
            field=models.TextField(default='Absence explanation'),
        ),
        migrations.AlterField(
            model_name='excuserequest',
            name='reason',
            field=models.CharField(choices=[('1', 'Sick'), ('2', 'Injured'), ('3', 'Other')], max_length=200),
        ),
    ]
